[simulation]
model_name = "BlackBirdsModel"
seed = 42
[space]
type = "continuous"
dimensions = [100, 100]
periodic = true
[agents]
state_type = "BlackBird"
speed = 1.0
cohere_factor = 0.1
separation = 2.0
separate_factor = 0.25
match_factor = 0.04
visual_distance = 5.0
[population]
pop_quantity = { "BlackBird" = 100 }
[rules]
agent_step = "agent_step!"
initialization_rule = "random"
[visualization]
filename = "output_videos/black_birds.mp4"
title = "Black Birds model"
variable_to_color = "state.status"
color_scheme = { BlackBird = "yellow" }
agent_shape = "arrow"
frames = 150
framerate = 20
