[simulation]
model_name = "RockPaperScissors"
seed = 42

[space]
type = "grid"
dimensions = [50, 50]
periodic = true

[properties]
threshold = 3

[agents]
state_type = "Symbol"

[population]
pop_density = { rock = 0.33, paper = 0.33, scissors = 0.34 }

[rules]
agent_step = "rps_step!"
model_step = "default_model_step!"
initialization_rule = "random"

[visualization]
filename = "output_videos/rps.mp4"
title = "Rock, Paper, Scissors!"
variable_to_color = "state"
color_scheme = { rock = "red", paper = "yellow", scissors = "green" }
agent_shape = { rock = "circle", scissors = "diamond", paper = "rect" }
framerate = 10
frames = 100